name: Production Deploy

on:
  push:
    branches:
      - main
      - deploy

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04
  
    steps:
    - uses: actions/checkout@v2

    - uses: deptno/action-aws-ssm-to-dotenv@v1.3.1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-northeast-2
      with:
        ssm-path: /ZENNBOT-CLIENT/PRODUCTION
        output: .env
        decryption: true

    - name: yarn install
      run: yarn install

    - name: build
      run: yarn build

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: zennbot-client-prd
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
        SOURCE_DIR: build
